---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Code
```{r}
SimAnt <- function(nSimulations, MaxMoves, Question){
  
  PossibleMoves <- c("Up","Down", "Left", "Right")
  TotalMoves <- 0
  Diverge <- FALSE
  
  for (i in 1:nSimulations){
    Coords <- c(0,0)
    names(Coords) <- c("x","y")
    NumberMoves <- 0
    
    while (!FoundFood(Coords, Question) & NumberMoves < MaxMoves){ 
      Move <- sample(PossibleMoves, 1, prob = c(rep(1/4,4)))
      NumberMoves = NumberMoves + 1
      
      if (Move == "Up") Coords["y"] = Coords["y"] + 10
      if (Move == "Down") Coords["y"] = Coords["y"] - 10
      if (Move == "Left") Coords["x"] = Coords["x"] - 10
      if (Move == "Right") Coords["x"] = Coords["x"] + 10
      
      if (NumberMoves == MaxMoves){
        Diverge <- TRUE
        print(paste("Reached", MaxMoves, 
                    "moves, box is likely not bounded and avg moves diverges", sep=" "))
        break
      }
    }
    if (Diverge){
      print("Stopping...")
      break
    }
    TotalMoves <- TotalMoves + NumberMoves
  }
  
  if (!Diverge){
    print(paste("Took",TotalMoves/nSimulations,"on average", sep=" "))
  }
}

FoundFood <- function(Coords, Question){
  
  if (Question == 1){
    if(Coords["x"] != 20 & 
       Coords["y"] != 20 & 
       Coords["x"] != -20 & 
       Coords["y"] != -20){
      return(FALSE)} else return(TRUE)
  }
  
  if (Question == 2){
    if (Coords["x"] + Coords["y"] < 10) return(FALSE) else return(TRUE)
  }
  
  if (Question == 3){
    if ((((Coords["x"]-2.5)/30)*2 + ((Coords["y"]-2.5)/40)*2) < 1) {
      return(FALSE)} else return(TRUE)
  }
}

```

### Question 1 
```{r}
SimAnt(nSimulations = 10000, MaxMoves = 10000, Question = 1)
```

Converges to $\mathbf{4.5}$ as $n \to \infty$

### Question 2 
```{r}
SimAnt(nSimulations = 10000, MaxMoves = 10000, Question = 2)
```

\textbf{Diverges} as the area is not bounded


### Question 3 
```{r}
SimAnt(nSimulations = 10000, MaxMoves = 10000, Question = 3)
```

\textbf{Diverges} as the area is not bounded

